---
url: https://www.emfink.net # the base hostname & protocol for your site
baseurl: /lj-folio # the subpath of your site, e.g. /blog/
title: Eric M. Fink
description:  # leave blank if you don't want to display a description 
last_updated: 7 September 2019 # leave blank if you don't want to display last updated


name: Eric M. Fink
position: Associate Professor
institution: Elon Law School
street: 201 North Greene Street
city: Greensboro
state: North Carolina
zip: '27401'
email: efink@elon.edu
phone: 336-279-9334

footer_text: >
  Created by <a href="https://github.com/LuckyJimJD" target="_blank">Eric M. Fink</a>. 
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a>. 
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>. 
  <br> 
  Original content licensed under a <a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/"> Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jekyll/scholar
    - jemoji

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
anchorjs_version: "3.2.2"
