---
url: https://www.emfink.net # the base hostname & protocol for your site
baseurl: /lj-folio # the subpath of your site, e.g. /blog/
title: Eric M. Fink
description:  # leave blank if you don't want to display a description 
last_updated: 1 December 2019 # leave blank if you don't want to display last updated


name: Eric M. Fink
position: Associate Professor
institution: Elon Law School
street: 201 North Greene Street
city: Greensboro
state: North Carolina
zip: '27401'
email: efink@elon.edu
phone: 336-279-9334

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    - jekyll-paginate
    - jemoji

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
anchorjs_version: "3.2.2"
